# This is the master CI workflow that runs the test suite on all pushes to master and all pull requests.
# It runs the following jobs:
# - required: runs the test suite on ubuntu with nightly toolchain
# - coverage: runs the test suite and collects coverage information
# See check.yml for information about how the concurrency cancelation and workflow triggering works

permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: test
env:
  CARGO_TERM_COLOR: always
jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu / nightly
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: set up python
        uses: quansight-labs/setup-python@v5
      - name: Install nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: cargo nextest
        run: |
          cargo nextest run --profile ci --no-fail-fast --all-targets --all-features --workspace
        continue-on-error: true
      - name: cargo test --doc
        run: |
          cargo test --doc
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: cargo llvm-cov
        run: cargo llvm-cov --locked --all-features --lcov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # - name: Upload test results to Codecov
      #   uses: codecov/test-results-action@v1.0.1 # v1.0.1
      #   with:
      #     fail_ci_if_error: true
      #     files: reports/results.xml
      #     token: ${{ secrets.CODECOV_TOKEN }}
